name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      home:
        description: 'location'
        required: false
        default: 'The Octoverse'

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name : "Test"
        id : "test"
        run: echo "::set-output name=Hello::${{ github.event.inputs.name }}!"
      
      - run: echo "The selected color is ${{ steps.test.outputs.Hello }}"
